"""Curated delivery jobs with exact, purposeful product bundles.

Each bundle is unique, uses one to five goods, and keeps finished products
separate from their production inputs so reservations cannot starve a job.
Amounts and rewards belong to the economy engine; this is content only.
See DELIVERY_RECIPES.md for the complete player-facing catalog.
"""

from __future__ import annotations


ORDER_RECIPES = (
    # 1-good jobs.
    {
        "id": "garden_salad_crates",
        "name": "Garden Salad Crates",
        "purpose": "The guesthouse kitchen needs tomatoes for its breakfast salad bar.",
        "goods": (
            "farm_tomatoes",
        ),
        "breakfast": True,
    },
    {
        "id": "omelet_counter",
        "name": "Omelet Counter",
        "purpose": "The breakfast cook needs eggs for the morning omelet station.",
        "goods": (
            "farm_eggs",
        ),
        "breakfast": True,
    },
    {
        "id": "tea_shop_sweetener",
        "name": "Tea Shop Sweetener",
        "purpose": "The tea shop needs honey for its morning drinks.",
        "goods": (
            "farm_honey",
        ),
        "breakfast": True,
    },
    {
        "id": "fish_supper_special",
        "name": "Fish Supper Special",
        "purpose": "The harbor diner needs fresh fish for tonight's special.",
        "goods": (
            "fish_stall_fresh_catch",
        ),
        "breakfast": False,
    },
    {
        "id": "oyster_bar_opening",
        "name": "Oyster Bar Opening",
        "purpose": "The waterfront oyster bar is stocking its opening service.",
        "goods": (
            "fish_stall_oysters",
        ),
        "breakfast": False,
    },
    {
        "id": "smoked_fish_toasts",
        "name": "Smoked Fish Toasts",
        "purpose": "The guesthouse needs smoked fish for its breakfast toast menu.",
        "goods": (
            "fish_stall_smoked_fish",
        ),
        "breakfast": True,
    },
    {
        "id": "office_coffee_refill",
        "name": "Office Coffee Refill",
        "purpose": "The office kitchen needs beans for its morning coffee grinder.",
        "goods": (
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "station_coffee_rush",
        "name": "Station Coffee Rush",
        "purpose": "The station kiosk needs espresso for the first commuter rush.",
        "goods": (
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "bakery_breakfast_tray",
        "name": "Bakery Breakfast Tray",
        "purpose": "The library cafe needs pastries for its morning reading group.",
        "goods": (
            "roastery_pastries",
        ),
        "breakfast": True,
    },
    {
        "id": "school_bus_checkup",
        "name": "School Bus Checkup",
        "purpose": "The school depot needs repair work before the morning bus run.",
        "goods": (
            "garage_repairs",
        ),
        "breakfast": False,
    },
    {
        "id": "workshop_spares_shelf",
        "name": "Workshop Spares Shelf",
        "purpose": "The neighborhood mechanic is restocking replacement parts.",
        "goods": (
            "garage_spare_parts",
        ),
        "breakfast": False,
    },
    {
        "id": "accessible_taxi_upgrade",
        "name": "Accessible Taxi Upgrade",
        "purpose": "The taxi service needs custom modifications for accessible vehicles.",
        "goods": (
            "garage_custom_mods",
        ),
        "breakfast": False,
    },
    {
        "id": "library_shelf_supports",
        "name": "Library Shelf Supports",
        "purpose": "The library needs steel brackets to secure new reading-room shelves.",
        "goods": (
            "workshop_steel_brackets",
        ),
        "breakfast": False,
    },
    {
        "id": "market_stall_skeletons",
        "name": "Market Stall Skeletons",
        "purpose": "The street market needs welded frames for permanent vendor stalls.",
        "goods": (
            "workshop_welded_frames",
        ),
        "breakfast": False,
    },
    {
        "id": "bridge_fastener_refit",
        "name": "Bridge Fastener Refit",
        "purpose": "The bridge crew needs precision bolts to replace worn fasteners.",
        "goods": (
            "workshop_machined_bolts",
        ),
        "breakfast": False,
    },
    {
        "id": "school_daylight_power",
        "name": "School Daylight Power",
        "purpose": "The school buys solar electricity for daytime classrooms.",
        "goods": (
            "solar_coop_daytime_kwh",
        ),
        "breakfast": False,
    },
    {
        "id": "clinic_battery_backup",
        "name": "Clinic Battery Backup",
        "purpose": "The clinic needs stored energy to keep its equipment running.",
        "goods": (
            "solar_coop_battery_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "festival_carbon_fund",
        "name": "Festival Carbon Fund",
        "purpose": "The festival organizer buys credits for its travel footprint.",
        "goods": (
            "solar_coop_carbon_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "emergency_pantry_refill",
        "name": "Emergency Pantry Refill",
        "purpose": "The community shelter needs shelf-stable meals for its pantry.",
        "goods": (
            "cannery_canned_goods",
        ),
        "breakfast": False,
    },
    {
        "id": "diner_sauce_shelf",
        "name": "Diner Sauce Shelf",
        "purpose": "The diner needs sauces for its lunch and dinner counter.",
        "goods": (
            "cannery_sauces",
        ),
        "breakfast": False,
    },
    {
        "id": "toast_bar_toppings",
        "name": "Toast Bar Toppings",
        "purpose": "The hostel needs preserves for its morning toast bar.",
        "goods": (
            "cannery_preserves",
        ),
        "breakfast": True,
    },
    {
        "id": "assembly_line_refit",
        "name": "Assembly Line Refit",
        "purpose": "The factory needs CNC parts to replace worn assembly components.",
        "goods": (
            "machine_works_cnc_parts",
        ),
        "breakfast": False,
    },
    {
        "id": "apprentice_tool_kits",
        "name": "Apprentice Tool Kits",
        "purpose": "The trade school needs tooling for its next practical course.",
        "goods": (
            "machine_works_tooling",
        ),
        "breakfast": False,
    },
    {
        "id": "inventor_demo_models",
        "name": "Inventor Demo Models",
        "purpose": "The makers' fair needs working prototypes for its invention showcase.",
        "goods": (
            "machine_works_prototypes",
        ),
        "breakfast": False,
    },
    {
        "id": "evening_wind_supply",
        "name": "Evening Wind Supply",
        "purpose": "The evening market buys wind electricity for its stalls.",
        "goods": (
            "turbine_field_wind_kwh",
        ),
        "breakfast": False,
    },
    {
        "id": "winter_power_booking",
        "name": "Winter Power Booking",
        "purpose": "The town books generating capacity ahead of the winter rush.",
        "goods": (
            "turbine_field_capacity_contracts",
        ),
        "breakfast": False,
    },
    {
        "id": "green_venue_certification",
        "name": "Green Venue Certification",
        "purpose": "The conference venue needs certificates for its clean-power program.",
        "goods": (
            "turbine_field_green_certificates",
        ),
        "breakfast": False,
    },
    {
        "id": "hospital_steady_supply",
        "name": "Hospital Steady Supply",
        "purpose": "The hospital books steady electricity for round-the-clock care.",
        "goods": (
            "generator_baseload_power",
        ),
        "breakfast": False,
    },
    {
        "id": "stadium_match_power",
        "name": "Stadium Match Power",
        "purpose": "The stadium needs extra electricity for the evening match.",
        "goods": (
            "generator_peak_power",
        ),
        "breakfast": False,
    },
    {
        "id": "district_heating_round",
        "name": "District Heating Round",
        "purpose": "The housing cooperative buys steam heat for its buildings.",
        "goods": (
            "generator_steam_heat",
        ),
        "breakfast": False,
    },
    {
        "id": "library_internet_boost",
        "name": "Library Internet Boost",
        "purpose": "The public library needs bandwidth for its computer room.",
        "goods": (
            "relay_station_bandwidth",
        ),
        "breakfast": False,
    },
    {
        "id": "school_closure_alerts",
        "name": "School Closure Alerts",
        "purpose": "The school district needs text messages for family notifications.",
        "goods": (
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "valley_mobile_coverage",
        "name": "Valley Mobile Coverage",
        "purpose": "The rural network needs tower leases to extend mobile coverage.",
        "goods": (
            "relay_station_tower_leases",
        ),
        "breakfast": False,
    },
    {
        "id": "furniture_export_space",
        "name": "Furniture Export Space",
        "purpose": "The furniture cooperative books container space for its next shipment.",
        "goods": (
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "market_fridge_booking",
        "name": "Market Fridge Booking",
        "purpose": "The market books refrigerated space to protect fresh stock.",
        "goods": (
            "freight_terminal_cold_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "neighborhood_parcel_run",
        "name": "Neighborhood Parcel Run",
        "purpose": "The parcel shop books delivery service to customers' doors.",
        "goods": (
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "animation_render_queue",
        "name": "Animation Render Queue",
        "purpose": "The animation club needs computing time to finish its short film.",
        "goods": (
            "data_center_compute_hours",
        ),
        "breakfast": False,
    },
    {
        "id": "museum_digital_archive",
        "name": "Museum Digital Archive",
        "purpose": "The museum needs cloud storage for digitized photographs.",
        "goods": (
            "data_center_cloud_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "town_app_connection",
        "name": "Town App Connection",
        "purpose": "The town app needs API calls to keep its services up to date.",
        "goods": (
            "data_center_api_calls",
        ),
        "breakfast": False,
    },
    {
        "id": "factory_solar_supply",
        "name": "Factory Solar Supply",
        "purpose": "The industrial park buys utility-scale solar electricity.",
        "goods": (
            "solar_array_utility_kwh",
        ),
        "breakfast": False,
    },
    {
        "id": "heatwave_power_buffer",
        "name": "Heatwave Power Buffer",
        "purpose": "The town books reserve capacity before a week of heavy cooling demand.",
        "goods": (
            "solar_array_reserve_capacity",
        ),
        "breakfast": False,
    },
    {
        "id": "clean_campus_credits",
        "name": "Clean Campus Credits",
        "purpose": "The university buys renewable credits for its clean-energy program.",
        "goods": (
            "solar_array_renewable_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "island_internet_link",
        "name": "Island Internet Link",
        "purpose": "The island school needs satellite bandwidth for remote lessons.",
        "goods": (
            "uplink_center_satellite_bandwidth",
        ),
        "breakfast": False,
    },
    {
        "id": "satellite_contact_window",
        "name": "Satellite Contact Window",
        "purpose": "The space club books ground-station time to contact its satellite.",
        "goods": (
            "uplink_center_ground_time",
        ),
        "breakfast": False,
    },
    {
        "id": "river_sensor_readings",
        "name": "River Sensor Readings",
        "purpose": "The water authority needs telemetry to monitor river sensors.",
        "goods": (
            "uplink_center_telemetry",
        ),
        "breakfast": False,
    },
    # 2-good jobs.
    {
        "id": "farmhouse_omelet",
        "name": "Farmhouse Omelet",
        "purpose": "The village cafe pairs eggs with tomatoes for a fresh morning omelet.",
        "goods": (
            "farm_eggs",
            "farm_tomatoes",
        ),
        "breakfast": True,
    },
    {
        "id": "honey_custard_prep",
        "name": "Honey Custard Prep",
        "purpose": "The guesthouse kitchen needs eggs and honey for breakfast custards.",
        "goods": (
            "farm_eggs",
            "farm_honey",
        ),
        "breakfast": True,
    },
    {
        "id": "sweet_tomato_relish",
        "name": "Sweet Tomato Relish",
        "purpose": "The farm shop pairs tomatoes with honey for a sweet breakfast relish.",
        "goods": (
            "farm_tomatoes",
            "farm_honey",
        ),
        "breakfast": True,
    },
    {
        "id": "harbor_fish_stew",
        "name": "Harbor Fish Stew",
        "purpose": "The dockside kitchen combines fresh fish and tomatoes for its stew.",
        "goods": (
            "fish_stall_fresh_catch",
            "farm_tomatoes",
        ),
        "breakfast": False,
    },
    {
        "id": "shellfish_counter",
        "name": "Shellfish Counter",
        "purpose": "The fishmonger stocks fresh fish and oysters for the weekend counter.",
        "goods": (
            "fish_stall_fresh_catch",
            "fish_stall_oysters",
        ),
        "breakfast": False,
    },
    {
        "id": "smoked_fish_scramble",
        "name": "Smoked Fish Scramble",
        "purpose": "The breakfast cafe folds smoked fish into scrambled eggs.",
        "goods": (
            "fish_stall_smoked_fish",
            "farm_eggs",
        ),
        "breakfast": True,
    },
    {
        "id": "smoked_fish_salad",
        "name": "Smoked Fish Salad",
        "purpose": "The marina cafe pairs smoked fish with tomatoes for a light breakfast.",
        "goods": (
            "fish_stall_smoked_fish",
            "farm_tomatoes",
        ),
        "breakfast": True,
    },
    {
        "id": "honey_coffee_station",
        "name": "Honey Coffee Station",
        "purpose": "The inn stocks roasted beans and honey for its breakfast coffee station.",
        "goods": (
            "roastery_roasted_beans",
            "farm_honey",
        ),
        "breakfast": True,
    },
    {
        "id": "honey_espresso_break",
        "name": "Honey Espresso Break",
        "purpose": "The station cafe sweetens its morning espresso drinks with honey.",
        "goods": (
            "roastery_espresso_shots",
            "farm_honey",
        ),
        "breakfast": True,
    },
    {
        "id": "coffee_and_pastry_break",
        "name": "Coffee And Pastry Break",
        "purpose": "The office orders espresso and pastries for its morning meeting.",
        "goods": (
            "roastery_espresso_shots",
            "roastery_pastries",
        ),
        "breakfast": True,
    },
    {
        "id": "breakfast_bake_and_brew",
        "name": "Breakfast Bake And Brew",
        "purpose": "The guesthouse stocks pastries and beans for its breakfast counter.",
        "goods": (
            "roastery_roasted_beans",
            "roastery_pastries",
        ),
        "breakfast": True,
    },
    {
        "id": "preserve_pastry_tray",
        "name": "Preserve Pastry Tray",
        "purpose": "The bakery tops its breakfast pastries with fruit preserves.",
        "goods": (
            "roastery_pastries",
            "cannery_preserves",
        ),
        "breakfast": True,
    },
    {
        "id": "seafood_sauce_pairing",
        "name": "Seafood Sauce Pairing",
        "purpose": "The dockside grill needs fresh fish and sauces for its supper plates.",
        "goods": (
            "fish_stall_fresh_catch",
            "cannery_sauces",
        ),
        "breakfast": False,
    },
    {
        "id": "oyster_tasting_pairing",
        "name": "Oyster Tasting Pairing",
        "purpose": "The oyster bar serves shellfish with a selection of sauces.",
        "goods": (
            "fish_stall_oysters",
            "cannery_sauces",
        ),
        "breakfast": False,
    },
    {
        "id": "pantry_supper_kits",
        "name": "Pantry Supper Kits",
        "purpose": "The food bank pairs canned meals with sauces for family supper kits.",
        "goods": (
            "cannery_canned_goods",
            "cannery_sauces",
        ),
        "breakfast": False,
    },
    {
        "id": "fleet_service_visit",
        "name": "Fleet Service Visit",
        "purpose": "The delivery depot books repairs and replacement parts for its vans.",
        "goods": (
            "garage_repairs",
            "garage_spare_parts",
        ),
        "breakfast": False,
    },
    {
        "id": "vehicle_access_refit",
        "name": "Vehicle Access Refit",
        "purpose": "The community shuttle pairs repair work with accessibility modifications.",
        "goods": (
            "garage_repairs",
            "garage_custom_mods",
        ),
        "breakfast": False,
    },
    {
        "id": "market_stall_rebuild",
        "name": "Market Stall Rebuild",
        "purpose": "The market crew joins welded frames with steel brackets for new stalls.",
        "goods": (
            "workshop_welded_frames",
            "workshop_steel_brackets",
        ),
        "breakfast": False,
    },
    {
        "id": "footbridge_assembly",
        "name": "Footbridge Assembly",
        "purpose": "The park crew fastens welded frames with precision bolts.",
        "goods": (
            "workshop_welded_frames",
            "workshop_machined_bolts",
        ),
        "breakfast": False,
    },
    {
        "id": "machine_calibration_kit",
        "name": "Machine Calibration Kit",
        "purpose": "The factory pairs CNC components with tooling for a line calibration.",
        "goods": (
            "machine_works_cnc_parts",
            "machine_works_tooling",
        ),
        "breakfast": False,
    },
    {
        "id": "prototype_test_bench",
        "name": "Prototype Test Bench",
        "purpose": "The inventors' club needs prototypes and tooling for a test session.",
        "goods": (
            "machine_works_prototypes",
            "machine_works_tooling",
        ),
        "breakfast": False,
    },
    {
        "id": "solar_after_sunset",
        "name": "Solar After Sunset",
        "purpose": "The co-op pairs daytime solar generation with battery storage.",
        "goods": (
            "solar_coop_daytime_kwh",
            "solar_coop_battery_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "clean_workshop_power",
        "name": "Clean Workshop Power",
        "purpose": "The workshop pairs daytime solar electricity with carbon credits.",
        "goods": (
            "solar_coop_daytime_kwh",
            "solar_coop_carbon_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "wind_power_guarantee",
        "name": "Wind Power Guarantee",
        "purpose": "The town pairs wind generation with booked capacity for reliable supply.",
        "goods": (
            "turbine_field_wind_kwh",
            "turbine_field_capacity_contracts",
        ),
        "breakfast": False,
    },
    {
        "id": "certified_wind_booking",
        "name": "Certified Wind Booking",
        "purpose": "The hotel pairs wind electricity with green certificates.",
        "goods": (
            "turbine_field_wind_kwh",
            "turbine_field_green_certificates",
        ),
        "breakfast": False,
    },
    {
        "id": "grid_rush_cover",
        "name": "Grid Rush Cover",
        "purpose": "The tram operator books steady power plus extra electricity for rush hour.",
        "goods": (
            "generator_baseload_power",
            "generator_peak_power",
        ),
        "breakfast": False,
    },
    {
        "id": "apartment_winter_service",
        "name": "Apartment Winter Service",
        "purpose": "The housing co-op books steady power and steam heat for winter.",
        "goods": (
            "generator_baseload_power",
            "generator_steam_heat",
        ),
        "breakfast": False,
    },
    {
        "id": "community_network_launch",
        "name": "Community Network Launch",
        "purpose": "The council pairs internet bandwidth with mobile tower space.",
        "goods": (
            "relay_station_bandwidth",
            "relay_station_tower_leases",
        ),
        "breakfast": False,
    },
    {
        "id": "classroom_connection",
        "name": "Classroom Connection",
        "purpose": "The school pairs internet access with text-message updates to families.",
        "goods": (
            "relay_station_bandwidth",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "refrigerated_cargo_space",
        "name": "Refrigerated Cargo Space",
        "purpose": "The grocer books container space and refrigeration for chilled imports.",
        "goods": (
            "freight_terminal_container_slots",
            "freight_terminal_cold_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "parcel_hub_handoff",
        "name": "Parcel Hub Handoff",
        "purpose": "The parcel depot pairs container arrivals with doorstep delivery service.",
        "goods": (
            "freight_terminal_container_slots",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "neighborhood_cold_chain",
        "name": "Neighborhood Cold Chain",
        "purpose": "The grocer books chilled storage and home delivery for fresh orders.",
        "goods": (
            "freight_terminal_cold_storage",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "film_studio_archive",
        "name": "Film Studio Archive",
        "purpose": "The studio pairs computing time with cloud storage for its film project.",
        "goods": (
            "data_center_compute_hours",
            "data_center_cloud_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "shop_app_launch",
        "name": "Shop App Launch",
        "purpose": "The shop pairs cloud storage with API calls for its online catalog.",
        "goods": (
            "data_center_cloud_storage",
            "data_center_api_calls",
        ),
        "breakfast": False,
    },
    {
        "id": "solar_power_guarantee",
        "name": "Solar Power Guarantee",
        "purpose": "The industrial estate pairs solar supply with backup reserve capacity.",
        "goods": (
            "solar_array_utility_kwh",
            "solar_array_reserve_capacity",
        ),
        "breakfast": False,
    },
    {
        "id": "certified_solar_supply",
        "name": "Certified Solar Supply",
        "purpose": "The college pairs utility solar power with renewable credits.",
        "goods": (
            "solar_array_utility_kwh",
            "solar_array_renewable_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "satellite_school_link",
        "name": "Satellite School Link",
        "purpose": "The remote school pairs satellite bandwidth with ground-station time.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_ground_time",
        ),
        "breakfast": False,
    },
    {
        "id": "remote_sensor_link",
        "name": "Remote Sensor Link",
        "purpose": "The ranger station pairs satellite bandwidth with sensor telemetry.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_telemetry",
        ),
        "breakfast": False,
    },
    {
        "id": "chilled_seafood_pickup",
        "name": "Chilled Seafood Pickup",
        "purpose": "The fishmonger books fresh fish and refrigeration for the morning catch.",
        "goods": (
            "fish_stall_fresh_catch",
            "freight_terminal_cold_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "neighborhood_pantry_drop",
        "name": "Neighborhood Pantry Drop",
        "purpose": "The food bank pairs canned meals with home delivery for housebound locals.",
        "goods": (
            "cannery_canned_goods",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "smart_grid_readout",
        "name": "Smart Grid Readout",
        "purpose": "The utility pairs steady power supply with telemetry to track demand.",
        "goods": (
            "generator_baseload_power",
            "uplink_center_telemetry",
        ),
        "breakfast": False,
    },
    {
        "id": "assembly_parts_freight",
        "name": "Assembly Parts Freight",
        "purpose": "The manufacturer books CNC parts and container space for a factory refit.",
        "goods": (
            "machine_works_cnc_parts",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "remote_weather_archive",
        "name": "Remote Weather Archive",
        "purpose": "The weather station pairs sensor telemetry with cloud storage.",
        "goods": (
            "uplink_center_telemetry",
            "data_center_cloud_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "fleet_arrival_alerts",
        "name": "Fleet Arrival Alerts",
        "purpose": "The delivery depot pairs doorstep service with text-message updates.",
        "goods": (
            "freight_terminal_last_mile_delivery",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "district_heat_repair",
        "name": "District Heat Repair",
        "purpose": "The housing co-op books repairs and steam heat to restore winter service.",
        "goods": (
            "garage_repairs",
            "generator_steam_heat",
        ),
        "breakfast": False,
    },
    # 3-good jobs.
    {
        "id": "farm_breakfast_basket",
        "name": "Farm Breakfast Basket",
        "purpose": "The guesthouse prepares tomato omelets and honey custards for breakfast.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "farm_honey",
        ),
        "breakfast": True,
    },
    {
        "id": "fisherman_s_breakfast",
        "name": "Fisherman's Breakfast",
        "purpose": "The dock cafe plates tomato eggs with smoked fish for its early crew.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "fish_stall_smoked_fish",
        ),
        "breakfast": True,
    },
    {
        "id": "early_shift_breakfast",
        "name": "Early Shift Breakfast",
        "purpose": "The depot cafe serves tomato omelets with espresso before the first shift.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "village_coffee_morning",
        "name": "Village Coffee Morning",
        "purpose": "The community hall serves freshly brewed coffee beside tomato egg dishes.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "honey_egg_coffee_set",
        "name": "Honey Egg Coffee Set",
        "purpose": "The farmstay serves honey custards with freshly brewed coffee.",
        "goods": (
            "farm_eggs",
            "farm_honey",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "honey_espresso_custards",
        "name": "Honey Espresso Custards",
        "purpose": "The cafe serves egg-and-honey custards with morning espresso.",
        "goods": (
            "farm_eggs",
            "farm_honey",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "marina_pastry_breakfast",
        "name": "Marina Pastry Breakfast",
        "purpose": "The marina cafe serves smoked fish, pastries and espresso to early sailors.",
        "goods": (
            "fish_stall_smoked_fish",
            "roastery_pastries",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "bakery_tasting_morning",
        "name": "Bakery Tasting Morning",
        "purpose": "The bakery pairs espresso with pastries and fruit preserves.",
        "goods": (
            "roastery_espresso_shots",
            "roastery_pastries",
            "cannery_preserves",
        ),
        "breakfast": True,
    },
    {
        "id": "ferry_breakfast_counter",
        "name": "Ferry Breakfast Counter",
        "purpose": "The ferry cafe stocks coffee beans, pastries and smoked fish for breakfast.",
        "goods": (
            "roastery_roasted_beans",
            "roastery_pastries",
            "fish_stall_smoked_fish",
        ),
        "breakfast": True,
    },
    {
        "id": "harbor_seafood_feast",
        "name": "Harbor Seafood Feast",
        "purpose": "The harbor restaurant serves fish and oysters with its house sauces.",
        "goods": (
            "fish_stall_fresh_catch",
            "fish_stall_oysters",
            "cannery_sauces",
        ),
        "breakfast": False,
    },
    {
        "id": "seaside_grill_plates",
        "name": "Seaside Grill Plates",
        "purpose": "The beach grill plates fresh fish with tomatoes and sauces.",
        "goods": (
            "fish_stall_fresh_catch",
            "farm_tomatoes",
            "cannery_sauces",
        ),
        "breakfast": False,
    },
    {
        "id": "emergency_meal_packs",
        "name": "Emergency Meal Packs",
        "purpose": "The shelter pairs canned meals, sauces and preserves for family food packs.",
        "goods": (
            "cannery_canned_goods",
            "cannery_sauces",
            "cannery_preserves",
        ),
        "breakfast": False,
    },
    {
        "id": "fish_breakfast_glaze",
        "name": "Fish Breakfast Glaze",
        "purpose": "The inn serves honey-glazed smoked fish beside tomato breakfast plates.",
        "goods": (
            "farm_tomatoes",
            "farm_honey",
            "fish_stall_smoked_fish",
        ),
        "breakfast": True,
    },
    {
        "id": "weekend_market_brunch",
        "name": "Weekend Market Brunch",
        "purpose": "The waterfront cafe serves oysters, smoked fish and tomato brunch plates.",
        "goods": (
            "fish_stall_oysters",
            "fish_stall_smoked_fish",
            "farm_tomatoes",
        ),
        "breakfast": True,
    },
    {
        "id": "tour_bus_service_pack",
        "name": "Tour Bus Service Pack",
        "purpose": "The bus depot combines repairs, spare parts and new frame sections.",
        "goods": (
            "garage_repairs",
            "garage_spare_parts",
            "workshop_welded_frames",
        ),
        "breakfast": False,
    },
    {
        "id": "playground_frame_build",
        "name": "Playground Frame Build",
        "purpose": "The parks crew combines frames, precision bolts and assembly tooling.",
        "goods": (
            "workshop_welded_frames",
            "workshop_machined_bolts",
            "machine_works_tooling",
        ),
        "breakfast": False,
    },
    {
        "id": "accessible_shuttle_build",
        "name": "Accessible Shuttle Build",
        "purpose": "The shuttle depot combines repairs, custom modifications and new frames.",
        "goods": (
            "garage_repairs",
            "garage_custom_mods",
            "workshop_welded_frames",
        ),
        "breakfast": False,
    },
    {
        "id": "factory_precision_refit",
        "name": "Factory Precision Refit",
        "purpose": "The factory pairs CNC parts and precision bolts with calibration tooling.",
        "goods": (
            "machine_works_cnc_parts",
            "workshop_machined_bolts",
            "machine_works_tooling",
        ),
        "breakfast": False,
    },
    {
        "id": "inventor_trial_run",
        "name": "Inventor Trial Run",
        "purpose": "The makers' club pairs prototypes and tooling with power for its test bench.",
        "goods": (
            "machine_works_prototypes",
            "machine_works_tooling",
            "solar_coop_daytime_kwh",
        ),
        "breakfast": False,
    },
    {
        "id": "rooftop_evening_supply",
        "name": "Rooftop Evening Supply",
        "purpose": "The housing co-op combines solar generation, batteries and carbon credits.",
        "goods": (
            "solar_coop_daytime_kwh",
            "solar_coop_battery_storage",
            "solar_coop_carbon_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "school_power_reserve",
        "name": "School Power Reserve",
        "purpose": "The school combines solar power, battery storage and booked wind capacity.",
        "goods": (
            "solar_coop_daytime_kwh",
            "solar_coop_battery_storage",
            "turbine_field_capacity_contracts",
        ),
        "breakfast": False,
    },
    {
        "id": "wind_farm_service_visit",
        "name": "Wind Farm Service Visit",
        "purpose": "The wind operator books repairs, CNC parts and wind output for a restart.",
        "goods": (
            "garage_repairs",
            "machine_works_cnc_parts",
            "turbine_field_wind_kwh",
        ),
        "breakfast": False,
    },
    {
        "id": "reliable_night_market",
        "name": "Reliable Night Market",
        "purpose": "The night market books wind power, battery storage and green certificates.",
        "goods": (
            "turbine_field_wind_kwh",
            "solar_coop_battery_storage",
            "turbine_field_green_certificates",
        ),
        "breakfast": False,
    },
    {
        "id": "winter_housing_package",
        "name": "Winter Housing Package",
        "purpose": "The housing co-op books steady power, peak cover and steam heat.",
        "goods": (
            "generator_baseload_power",
            "generator_peak_power",
            "generator_steam_heat",
        ),
        "breakfast": False,
    },
    {
        "id": "festival_mobile_network",
        "name": "Festival Mobile Network",
        "purpose": "The festival books bandwidth, tower space and text alerts for visitors.",
        "goods": (
            "relay_station_bandwidth",
            "relay_station_tower_leases",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "chilled_harbor_freight",
        "name": "Chilled Harbor Freight",
        "purpose": "The fish exporter books fresh fish, refrigeration and container space.",
        "goods": (
            "fish_stall_fresh_catch",
            "freight_terminal_cold_storage",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "pantry_doorstep_route",
        "name": "Pantry Doorstep Route",
        "purpose": "The food bank sends canned meals and preserves through home delivery.",
        "goods": (
            "cannery_canned_goods",
            "cannery_preserves",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "game_studio_launch",
        "name": "Game Studio Launch",
        "purpose": "The game studio books computing time, cloud storage and API calls.",
        "goods": (
            "data_center_compute_hours",
            "data_center_cloud_storage",
            "data_center_api_calls",
        ),
        "breakfast": False,
    },
    {
        "id": "solar_campus_contract",
        "name": "Solar Campus Contract",
        "purpose": "The university combines utility solar power, reserve cover and clean credits.",
        "goods": (
            "solar_array_utility_kwh",
            "solar_array_reserve_capacity",
            "solar_array_renewable_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "ocean_buoy_link",
        "name": "Ocean Buoy Link",
        "purpose": "The ocean lab books satellite bandwidth, ground time and sensor telemetry.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_ground_time",
            "uplink_center_telemetry",
        ),
        "breakfast": False,
    },
    {
        "id": "school_digital_lessons",
        "name": "School Digital Lessons",
        "purpose": "The school pairs bandwidth, cloud storage and computing time for lessons.",
        "goods": (
            "relay_station_bandwidth",
            "data_center_cloud_storage",
            "data_center_compute_hours",
        ),
        "breakfast": False,
    },
    {
        "id": "cold_room_power_cover",
        "name": "Cold Room Power Cover",
        "purpose": "The grocer pairs refrigeration with steady power and battery backup.",
        "goods": (
            "freight_terminal_cold_storage",
            "generator_baseload_power",
            "solar_coop_battery_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "city_delivery_dashboard",
        "name": "City Delivery Dashboard",
        "purpose": "The parcel depot pairs home delivery with cloud records and API calls.",
        "goods": (
            "freight_terminal_last_mile_delivery",
            "data_center_cloud_storage",
            "data_center_api_calls",
        ),
        "breakfast": False,
    },
    {
        "id": "remote_research_archive",
        "name": "Remote Research Archive",
        "purpose": "The field lab pairs telemetry, satellite bandwidth and cloud archives.",
        "goods": (
            "uplink_center_telemetry",
            "uplink_center_satellite_bandwidth",
            "data_center_cloud_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "heat_network_retrofit",
        "name": "Heat Network Retrofit",
        "purpose": "The heating crew books repairs, CNC parts and steam heat for a district refit.",
        "goods": (
            "garage_repairs",
            "machine_works_cnc_parts",
            "generator_steam_heat",
        ),
        "breakfast": False,
    },
    # 4-good jobs.
    {
        "id": "harbor_sunrise_buffet",
        "name": "Harbor Sunrise Buffet",
        "purpose": "The dockside inn serves tomato eggs, smoked fish and freshly brewed coffee.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "fish_stall_smoked_fish",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "marina_espresso_brunch",
        "name": "Marina Espresso Brunch",
        "purpose": "The marina cafe serves tomato eggs, smoked fish and espresso to early crews.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "fish_stall_smoked_fish",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "farmstay_coffee_table",
        "name": "Farmstay Coffee Table",
        "purpose": "The farmstay serves tomato omelets, honey custards and freshly brewed coffee.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "farm_honey",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "village_espresso_breakfast",
        "name": "Village Espresso Breakfast",
        "purpose": "The village cafe serves tomato eggs and honey custards with espresso.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "farm_honey",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "coastal_breakfast_board",
        "name": "Coastal Breakfast Board",
        "purpose": "The inn pairs tomato and smoked-fish plates with pastries and espresso.",
        "goods": (
            "farm_tomatoes",
            "fish_stall_smoked_fish",
            "roastery_pastries",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "guesthouse_breakfast_spread",
        "name": "Guesthouse Breakfast Spread",
        "purpose": "The guesthouse offers smoked fish, pastries, preserves and brewed coffee.",
        "goods": (
            "fish_stall_smoked_fish",
            "roastery_pastries",
            "cannery_preserves",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "harbor_coffee_tasting",
        "name": "Harbor Coffee Tasting",
        "purpose": "The harbor cafe serves oysters, smoked fish and pastries with espresso.",
        "goods": (
            "fish_stall_oysters",
            "fish_stall_smoked_fish",
            "roastery_pastries",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "community_pantry_pallets",
        "name": "Community Pantry Pallets",
        "purpose": "The food bank books canned meals, sauces, preserves and container space.",
        "goods": (
            "cannery_canned_goods",
            "cannery_sauces",
            "cannery_preserves",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "chilled_seafood_showcase",
        "name": "Chilled Seafood Showcase",
        "purpose": "The market stocks fresh fish, oysters and sauces with refrigerated space.",
        "goods": (
            "fish_stall_fresh_catch",
            "fish_stall_oysters",
            "cannery_sauces",
            "freight_terminal_cold_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "shuttle_workshop_refit",
        "name": "Shuttle Workshop Refit",
        "purpose": "The bus depot combines repairs, spare parts, frame sections and tooling.",
        "goods": (
            "garage_repairs",
            "garage_spare_parts",
            "workshop_welded_frames",
            "machine_works_tooling",
        ),
        "breakfast": False,
    },
    {
        "id": "park_footbridge_build",
        "name": "Park Footbridge Build",
        "purpose": "The parks crew orders frames, precision bolts, CNC parts and tooling.",
        "goods": (
            "workshop_welded_frames",
            "workshop_machined_bolts",
            "machine_works_cnc_parts",
            "machine_works_tooling",
        ),
        "breakfast": False,
    },
    {
        "id": "accessible_fleet_rollout",
        "name": "Accessible Fleet Rollout",
        "purpose": "The council pairs repairs, custom modifications and frames with freight space.",
        "goods": (
            "garage_repairs",
            "garage_custom_mods",
            "workshop_welded_frames",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "clean_prototype_workshop",
        "name": "Clean Prototype Workshop",
        "purpose": "The makers' lab powers prototype tests with solar supply, batteries and tools.",
        "goods": (
            "machine_works_prototypes",
            "machine_works_tooling",
            "solar_coop_daytime_kwh",
            "solar_coop_battery_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "repair_crew_dispatch",
        "name": "Repair Crew Dispatch",
        "purpose": "The mobile mechanic books repairs, CNC parts, tooling and home delivery.",
        "goods": (
            "garage_repairs",
            "machine_works_cnc_parts",
            "machine_works_tooling",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "neighborhood_microgrid",
        "name": "Neighborhood Microgrid",
        "purpose": "The neighborhood combines solar and wind generation, batteries and capacity.",
        "goods": (
            "solar_coop_daytime_kwh",
            "turbine_field_wind_kwh",
            "solar_coop_battery_storage",
            "turbine_field_capacity_contracts",
        ),
        "breakfast": False,
    },
    {
        "id": "certified_night_supply",
        "name": "Certified Night Supply",
        "purpose": "The night market books wind generation, batteries, capacity and certificates.",
        "goods": (
            "turbine_field_wind_kwh",
            "solar_coop_battery_storage",
            "turbine_field_capacity_contracts",
            "turbine_field_green_certificates",
        ),
        "breakfast": False,
    },
    {
        "id": "housing_winter_guarantee",
        "name": "Housing Winter Guarantee",
        "purpose": "The housing co-op books steady power, peak cover, heat and reserve capacity.",
        "goods": (
            "generator_baseload_power",
            "generator_peak_power",
            "generator_steam_heat",
            "solar_array_reserve_capacity",
        ),
        "breakfast": False,
    },
    {
        "id": "festival_signal_backup",
        "name": "Festival Signal Backup",
        "purpose": "The festival supports bandwidth, tower leases and text alerts with batteries.",
        "goods": (
            "relay_station_bandwidth",
            "relay_station_tower_leases",
            "relay_station_sms_traffic",
            "solar_coop_battery_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "harbor_cold_chain",
        "name": "Harbor Cold Chain",
        "purpose": "The seafood exporter books fresh fish, chilled containers and steady power.",
        "goods": (
            "fish_stall_fresh_catch",
            "freight_terminal_cold_storage",
            "freight_terminal_container_slots",
            "generator_baseload_power",
        ),
        "breakfast": False,
    },
    {
        "id": "mobile_pantry_network",
        "name": "Mobile Pantry Network",
        "purpose": "The food bank pairs canned meals and preserves with deliveries and text alerts.",
        "goods": (
            "cannery_canned_goods",
            "cannery_preserves",
            "freight_terminal_last_mile_delivery",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "game_launch_capacity",
        "name": "Game Launch Capacity",
        "purpose": "The studio supports compute, cloud storage and API traffic with reserve power.",
        "goods": (
            "data_center_compute_hours",
            "data_center_cloud_storage",
            "data_center_api_calls",
            "solar_array_reserve_capacity",
        ),
        "breakfast": False,
    },
    {
        "id": "clean_data_hosting",
        "name": "Clean Data Hosting",
        "purpose": "The cloud firm combines compute and storage with solar power and clean credits.",
        "goods": (
            "data_center_compute_hours",
            "data_center_cloud_storage",
            "solar_array_utility_kwh",
            "solar_array_renewable_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "school_connection_backup",
        "name": "School Connection Backup",
        "purpose": "The school pairs bandwidth and cloud lessons with batteries and text alerts.",
        "goods": (
            "relay_station_bandwidth",
            "data_center_cloud_storage",
            "solar_coop_battery_storage",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "island_science_link",
        "name": "Island Science Link",
        "purpose": "The island lab pairs satellite contact and telemetry with a cloud archive.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_ground_time",
            "uplink_center_telemetry",
            "data_center_cloud_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "town_parcel_platform",
        "name": "Town Parcel Platform",
        "purpose": "The parcel depot pairs home delivery, text updates, cloud records and API calls.",
        "goods": (
            "freight_terminal_last_mile_delivery",
            "relay_station_sms_traffic",
            "data_center_cloud_storage",
            "data_center_api_calls",
        ),
        "breakfast": False,
    },
    {
        "id": "transit_energy_hub",
        "name": "Transit Energy Hub",
        "purpose": "The tram depot combines utility solar, batteries, reserve power and repairs.",
        "goods": (
            "solar_array_utility_kwh",
            "solar_coop_battery_storage",
            "solar_array_reserve_capacity",
            "garage_repairs",
        ),
        "breakfast": False,
    },
    {
        "id": "winter_heating_rebuild",
        "name": "Winter Heating Rebuild",
        "purpose": "The heating crew pairs repairs, CNC parts and steam heat with new frames.",
        "goods": (
            "garage_repairs",
            "machine_works_cnc_parts",
            "generator_steam_heat",
            "workshop_welded_frames",
        ),
        "breakfast": False,
    },
    {
        "id": "fresh_market_route",
        "name": "Fresh Market Route",
        "purpose": "The grocer pairs tomatoes and eggs with refrigeration and home delivery.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "freight_terminal_cold_storage",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "factory_export_readiness",
        "name": "Factory Export Readiness",
        "purpose": "The manufacturer pairs CNC parts and tooling with freight space and repairs.",
        "goods": (
            "machine_works_cnc_parts",
            "machine_works_tooling",
            "freight_terminal_container_slots",
            "garage_repairs",
        ),
        "breakfast": False,
    },
    {
        "id": "clean_campus_assurance",
        "name": "Clean Campus Assurance",
        "purpose": "The university books solar supply, reserves, renewable credits and carbon credits.",
        "goods": (
            "solar_array_utility_kwh",
            "solar_array_reserve_capacity",
            "solar_array_renewable_credits",
            "solar_coop_carbon_credits",
        ),
        "breakfast": False,
    },
    # 5-good jobs.
    {
        "id": "harbor_breakfast_service",
        "name": "Harbor Breakfast Service",
        "purpose": "The harbor inn serves tomato eggs, honey, smoked fish and brewed coffee.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "farm_honey",
            "fish_stall_smoked_fish",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "marina_morning_banquet",
        "name": "Marina Morning Banquet",
        "purpose": "The marina serves tomato eggs, honey, smoked fish and espresso to guests.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "farm_honey",
            "fish_stall_smoked_fish",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "coastal_guesthouse_buffet",
        "name": "Coastal Guesthouse Buffet",
        "purpose": "The guesthouse serves tomatoes, smoked fish, oysters, pastries and espresso.",
        "goods": (
            "farm_tomatoes",
            "fish_stall_smoked_fish",
            "fish_stall_oysters",
            "roastery_pastries",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "seaside_coffee_spread",
        "name": "Seaside Coffee Spread",
        "purpose": "The inn stocks tomatoes, smoked fish, oysters, pastries and beans for brunch.",
        "goods": (
            "farm_tomatoes",
            "fish_stall_smoked_fish",
            "fish_stall_oysters",
            "roastery_pastries",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "breakfast_club_celebration",
        "name": "Breakfast Club Celebration",
        "purpose": "The breakfast club serves smoked fish, tomatoes, pastries, preserves and espresso.",
        "goods": (
            "fish_stall_smoked_fish",
            "farm_tomatoes",
            "roastery_pastries",
            "cannery_preserves",
            "roastery_espresso_shots",
        ),
        "breakfast": True,
    },
    {
        "id": "harbor_tasting_morning",
        "name": "Harbor Tasting Morning",
        "purpose": "The harbor cafe serves oysters, smoked fish, pastries, preserves and coffee.",
        "goods": (
            "fish_stall_oysters",
            "fish_stall_smoked_fish",
            "roastery_pastries",
            "cannery_preserves",
            "roastery_roasted_beans",
        ),
        "breakfast": True,
    },
    {
        "id": "pantry_relief_convoy",
        "name": "Pantry Relief Convoy",
        "purpose": "The relief team ships canned meals, sauces and preserves with vans and containers.",
        "goods": (
            "cannery_canned_goods",
            "cannery_sauces",
            "cannery_preserves",
            "freight_terminal_last_mile_delivery",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "seafood_export_launch",
        "name": "Seafood Export Launch",
        "purpose": "The exporter books fish, oysters, chilled containers and steady power.",
        "goods": (
            "fish_stall_fresh_catch",
            "fish_stall_oysters",
            "freight_terminal_cold_storage",
            "freight_terminal_container_slots",
            "generator_baseload_power",
        ),
        "breakfast": False,
    },
    {
        "id": "community_bridge_project",
        "name": "Community Bridge Project",
        "purpose": "The parks crew combines frames, bolts, CNC parts, tooling and delivery service.",
        "goods": (
            "workshop_welded_frames",
            "workshop_machined_bolts",
            "machine_works_cnc_parts",
            "machine_works_tooling",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "accessible_fleet_program",
        "name": "Accessible Fleet Program",
        "purpose": "The council orders repairs, custom modifications, frames, bolts and freight space.",
        "goods": (
            "garage_repairs",
            "garage_custom_mods",
            "workshop_welded_frames",
            "workshop_machined_bolts",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "inventor_campus_opening",
        "name": "Inventor Campus Opening",
        "purpose": "The makers' campus pairs prototypes, tools and CNC parts with solar and batteries.",
        "goods": (
            "machine_works_prototypes",
            "machine_works_tooling",
            "machine_works_cnc_parts",
            "solar_coop_daytime_kwh",
            "solar_coop_battery_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "town_microgrid_launch",
        "name": "Town Microgrid Launch",
        "purpose": "The council combines solar and wind output, batteries, capacity and carbon credits.",
        "goods": (
            "solar_coop_daytime_kwh",
            "turbine_field_wind_kwh",
            "solar_coop_battery_storage",
            "turbine_field_capacity_contracts",
            "solar_coop_carbon_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "winter_housing_recovery",
        "name": "Winter Housing Recovery",
        "purpose": "The housing co-op pairs repairs with steady power, peak cover, heat and reserves.",
        "goods": (
            "garage_repairs",
            "generator_baseload_power",
            "generator_peak_power",
            "generator_steam_heat",
            "solar_array_reserve_capacity",
        ),
        "breakfast": False,
    },
    {
        "id": "festival_network_command",
        "name": "Festival Network Command",
        "purpose": "The festival combines bandwidth, towers, text alerts, batteries and cloud records.",
        "goods": (
            "relay_station_bandwidth",
            "relay_station_tower_leases",
            "relay_station_sms_traffic",
            "solar_coop_battery_storage",
            "data_center_cloud_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "city_pantry_outreach",
        "name": "City Pantry Outreach",
        "purpose": "The food bank sends canned meals, sauces and preserves with deliveries and texts.",
        "goods": (
            "cannery_canned_goods",
            "cannery_sauces",
            "cannery_preserves",
            "freight_terminal_last_mile_delivery",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "online_school_campus",
        "name": "Online School Campus",
        "purpose": "The school combines bandwidth, compute, cloud storage, batteries and text alerts.",
        "goods": (
            "relay_station_bandwidth",
            "data_center_compute_hours",
            "data_center_cloud_storage",
            "solar_coop_battery_storage",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "studio_release_weekend",
        "name": "Studio Release Weekend",
        "purpose": "The studio combines compute, cloud storage, APIs, reserve power and text alerts.",
        "goods": (
            "data_center_compute_hours",
            "data_center_cloud_storage",
            "data_center_api_calls",
            "solar_array_reserve_capacity",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "clean_cloud_campus",
        "name": "Clean Cloud Campus",
        "purpose": "The data campus pairs compute and storage with utility solar, reserves and credits.",
        "goods": (
            "data_center_compute_hours",
            "data_center_cloud_storage",
            "solar_array_utility_kwh",
            "solar_array_reserve_capacity",
            "solar_array_renewable_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "island_research_station",
        "name": "Island Research Station",
        "purpose": "The lab combines satellite links, ground time, telemetry, archives and batteries.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_ground_time",
            "uplink_center_telemetry",
            "data_center_cloud_storage",
            "solar_coop_battery_storage",
        ),
        "breakfast": False,
    },
    {
        "id": "city_parcel_network",
        "name": "City Parcel Network",
        "purpose": "The courier pairs home delivery, texts, cloud records and APIs with container space.",
        "goods": (
            "freight_terminal_last_mile_delivery",
            "relay_station_sms_traffic",
            "data_center_cloud_storage",
            "data_center_api_calls",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "remote_clinic_connection",
        "name": "Remote Clinic Connection",
        "purpose": "The clinic combines satellite links, telemetry, cloud records, batteries and texts.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_telemetry",
            "data_center_cloud_storage",
            "solar_coop_battery_storage",
            "relay_station_sms_traffic",
        ),
        "breakfast": False,
    },
    {
        "id": "cold_market_opening",
        "name": "Cold Market Opening",
        "purpose": "The grocer stocks tomatoes and eggs with refrigeration, steady power and delivery.",
        "goods": (
            "farm_tomatoes",
            "farm_eggs",
            "freight_terminal_cold_storage",
            "generator_baseload_power",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "factory_export_program",
        "name": "Factory Export Program",
        "purpose": "The manufacturer pairs CNC parts, tooling and repairs with frames and cargo space.",
        "goods": (
            "machine_works_cnc_parts",
            "machine_works_tooling",
            "garage_repairs",
            "workshop_welded_frames",
            "freight_terminal_container_slots",
        ),
        "breakfast": False,
    },
    {
        "id": "district_heat_renewal",
        "name": "District Heat Renewal",
        "purpose": "The heating crew books repairs, CNC parts, frames, steam heat and reserve power.",
        "goods": (
            "garage_repairs",
            "machine_works_cnc_parts",
            "workshop_welded_frames",
            "generator_steam_heat",
            "solar_array_reserve_capacity",
        ),
        "breakfast": False,
    },
    {
        "id": "clean_transit_expansion",
        "name": "Clean Transit Expansion",
        "purpose": "The tram operator pairs repairs and batteries with utility solar, reserves and credits.",
        "goods": (
            "garage_repairs",
            "solar_coop_battery_storage",
            "solar_array_utility_kwh",
            "solar_array_reserve_capacity",
            "solar_array_renewable_credits",
        ),
        "breakfast": False,
    },
    {
        "id": "ocean_watch_network",
        "name": "Ocean Watch Network",
        "purpose": "The coastguard combines satellite contact, telemetry, archives and API reporting.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_ground_time",
            "uplink_center_telemetry",
            "data_center_cloud_storage",
            "data_center_api_calls",
        ),
        "breakfast": False,
    },
    {
        "id": "rural_learning_link",
        "name": "Rural Learning Link",
        "purpose": "The rural school combines satellite contact, cloud lessons, compute and solar supply.",
        "goods": (
            "uplink_center_satellite_bandwidth",
            "uplink_center_ground_time",
            "data_center_cloud_storage",
            "data_center_compute_hours",
            "solar_array_utility_kwh",
        ),
        "breakfast": False,
    },
    {
        "id": "emergency_signal_network",
        "name": "Emergency Signal Network",
        "purpose": "The rescue team combines tower space, satellite links, texts, batteries and reserves.",
        "goods": (
            "relay_station_tower_leases",
            "uplink_center_satellite_bandwidth",
            "relay_station_sms_traffic",
            "solar_coop_battery_storage",
            "solar_array_reserve_capacity",
        ),
        "breakfast": False,
    },
    {
        "id": "workshop_shipping_hub",
        "name": "Workshop Shipping Hub",
        "purpose": "The repair co-op combines CNC parts, tools and repairs with cargo space and delivery.",
        "goods": (
            "machine_works_cnc_parts",
            "machine_works_tooling",
            "garage_repairs",
            "freight_terminal_container_slots",
            "freight_terminal_last_mile_delivery",
        ),
        "breakfast": False,
    },
    {
        "id": "solar_estate_power_plan",
        "name": "Solar Estate Power Plan",
        "purpose": "The estate combines solar output, storage, reserves, carbon and renewable credits.",
        "goods": (
            "solar_array_utility_kwh",
            "solar_coop_battery_storage",
            "solar_array_reserve_capacity",
            "solar_coop_carbon_credits",
            "solar_array_renewable_credits",
        ),
        "breakfast": False,
    },
)
