#!/usr/bin/env python3
"""Generate the complete, public game asset list for the loading screen.

The loading screen downloads every shipped image, font, audio and video asset
before play. Editorial notes, prompt files and operating-system metadata are
excluded because the game never requests them and some cannot be served.

    python3 preload_manifest.py
    python3 preload_manifest.py --check
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "preload-manifest.js"
ASSET_SUFFIXES = frozenset({
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico",
    ".ttf", ".woff", ".woff2", ".otf",
    ".wav", ".mp3", ".ogg", ".mp4", ".webm",
})
REF_RE = re.compile(
    r"\.?/?((?:assets/[A-Za-z0-9_\-./]+|[A-Za-z0-9_\-]+)\.(?:png|svg|jpg|jpeg|gif|webp|ico|ttf|woff|woff2|otf|wav|mp3|ogg|mp4|webm))"
    r"(\?[A-Za-z0-9_\-=.&]*)?"
)


def source_files() -> list[Path]:
    """Only shipped top-level pages and scripts, not old copies in subfolders."""
    return [p for p in sorted(ROOT.glob("*"))
            if p.is_file() and p.suffix.lower() in (".html", ".css", ".js")
            and p != OUT]


def query_map() -> dict[str, list[str]]:
    """Keep every URL variant that live pages use so both cache keys are ready."""
    seen: dict[str, Counter] = defaultdict(Counter)
    for path in source_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for rel, query in REF_RE.findall(text):
            seen[rel][query or ""] += 1
    return {rel: [query for query, _ in counts.most_common()]
            for rel, counts in seen.items()}


def assets() -> list[Path]:
    paths = [p for p in (ROOT / "assets").rglob("*")
             if p.is_file() and p.suffix.lower() in ASSET_SUFFIXES]
    # The masthead is kept at the project root, outside assets/.
    paths.extend(p for p in ROOT.glob("*")
                 if p.is_file() and p.suffix.lower() in ASSET_SUFFIXES)
    return sorted(paths)


def build() -> dict:
    queries = query_map()
    entries: list[list] = []
    digest = hashlib.sha256()
    for path in assets():
        rel = path.relative_to(ROOT).as_posix()
        size = path.stat().st_size
        # If a same-size image changes, the manifest version must still change.
        digest.update(rel.encode("utf-8") + b"\0")
        with path.open("rb") as file:
            for chunk in iter(lambda: file.read(1024 * 1024), b""):
                digest.update(chunk)
        variants = queries.get(rel, [""])
        for query in variants:
            digest.update((rel + query).encode("utf-8") + b"\0")
            entries.append([rel + query, size])
    return {"all": entries, "version": digest.hexdigest()[:16]}


def render(data: dict) -> str:
    lines = [
        "/* Generated by preload_manifest.py - do not edit by hand.",
        "   Every public game image, font, audio and video file is downloaded",
        "   before the loading screen finishes. [url, uncompressed bytes]. */",
        "window.YomamaPreloadManifest = {",
        '  "all": [',
    ]
    lines.extend("    %s," % json.dumps(item, separators=(",", " "))
                 for item in data["all"])
    lines.extend(["  ],", '  "version": %s' % json.dumps(data["version"]), "};", ""])
    return "\n".join(lines)


def main() -> int:
    data = build()
    output = render(data)
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current == output:
            return 0
        print("preload-manifest.js is out of date; run python3 preload_manifest.py")
        return 1
    OUT.write_text(output, encoding="utf-8")
    total_mb = sum(size for _, size in data["all"]) / 1_000_000
    print("preload-manifest.js: %d URLs, %.1f MB" % (len(data["all"]), total_mb))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
